### ISSUE TITLE
RuntimeError when trying the quickstart example

### ISSUE THREAD

**Issue by LucaMarconato** [quadbiolab/latent-lego#1]
I am trying running the following [quickstart example](https://quadbiolab.github.io/latent-lego/quickstart/)

```
from latent.modules import VariationalEncoder, NegativeBinomialDecoder

# Creates a VariationalEncoder with a standard normal prior
encoder = VariationalEncoder(latent_dim=20, prior='normal', kld_weight=0.01)
# Creates a NegativeBinomialDecoder with a constant dispersion estimate
decoder = NegativeBinomialDecoder(x_dim=x_train.shape[1], dispersion='constant')

# Constructs an Autoencoder object with predefined encoder and decoder
ae = Autoencoder(
    encoder=encoder,
    decoder=decoder
)
ae.compile()

# Fit input data using size factors for each cell
x_sf = np.array([1.]*100)
ae.fit([x_train, x_sf], epochs=10, batch_size=10)
```

But on the line `encoder = VariationalEncoder(latent_dim=20, prior='normal', kld_weight=0.01)` I get the following error:

```
Traceback (most recent call last):
  File "/data/l989o/miniconda3/envs/39/lib/python3.9/site-packages/keras/engine/training.py", line 311, in __setattr__
    self._base_model_initialized
AttributeError: 'VariationalEncoder' object has no attribute '_base_model_initialized'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data/l989o/miniconda3/envs/39/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-56-9c41663c5e4a>", line 4, in <module>
    encoder = VariationalEncoder(latent_dim=20, prior='normal', kld_weight=0.01)
  File "/data/l989o/miniconda3/envs/39/lib/python3.9/site-packages/latent/modules/encoder.py", line 144, in __init__
    self.kld_weight = tf.Variable(kld_weight, trainable=False)
  File "/data/l989o/miniconda3/envs/39/lib/python3.9/site-packages/keras/engine/training.py", line 313, in __setattr__
    raise RuntimeError(
RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.
```

TensorFlow-related package configuration:
```
keras                     2.6.0                    pypi_0    pypi
tensorflow                2.6.0                    pypi_0    pypi
tensorflow-estimator      2.6.0                    pypi_0    pypi
tensorflow-probability    0.13.0                   pypi_0    pypi
```

**Comment by joschif** [comment]
Hi, this error seems to be related to the most recent version of tensorflow/keras. Using tensorflow version 2.5.0 should solve it for now. I'm working on making it compatible with th emost recent version.

**Comment by joschif** [comment]
I changed some stuff around so hopefully if you install the new version (0.2.1) from GitHub, it should also work with tf 2.6.0. Let me know how it goes :)
